#
# Sera - OnePage Jekyll Template
# Configuration File
#

# Information for compile
exclude: ["node_modules", "gulpfile.js", "package.json", "README.md"]

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: "Course: Writing Enterprise Level PHP"
description: "Learn how to write HQ maintainable software. Legacy code doesn't have to suck!"
default_blog_image: enterprise_level_php_course_thumbnail.jpg
# Website language
lang: en-US
# Header Title
header-title: Enterprise Level <strong>PHP</strong>
# Header Tagline
headter-tagline: Course

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: I want it!
  url: https://www.udemy.com/enterprise-php/

# Secondary Buttons
header-secondary-button:
  title: Hm, Tell me more
  url: "#about"

#
# If your website is placed in a separate folder on your server please modify
# this with your folder name, by default is empty.
# Example: Sera Demo is hosted on projects.gleesik.ro/sera-onepage
# If I compile Sera Template and I put in /sera-onepage without modifing baseurl
# than scripts can't be loaded corectly.
# For this example my site url is: projects.gleesik.ro (This can be just www.example.com)
# My folder for Demo Website is: /sera-onepage so baseurl: /sera-onepage
#
baseurl:

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: services@trki.sk

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: https://www.udemy.com/enterprise-php/

####################################
######  Global Social Links   ######
####################################
youtube: '#'
pinterest: '#'
facebook: 'https://www.facebook.com/lukas.lukac'
twitter: 'https://twitter.com/EnchanterIO'
twitter_username: 'EnchanterIO'
linkedin: 'https://www.linkedin.com/in/llukac'
google-plus: '#'
vimeo: '#'

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: lukas_lukac_profile.jpg
  author-name: Lukas Lukac
  author-tagline: Course Instructor
  author-info: Software Engineering, Psychology, Starcraft, Protein, Women && Motorbikes addict.
  author-social-links:
    youtube: '#'
    pinterest: '#'
    facebook: 'https://www.facebook.com/lukas.lukac'
    twitter: 'https://twitter.com/EnchanterIO'
    linkedin: 'https://www.linkedin.com/in/llukac'
    google-plus: '#'

# Google Map JS api
# This is my api for this template
key-api: AIzaSyDbnxVZQannH0GF4gtnnBFPiP9ofm2WqGs
map-text: Sera Google Map
map-text-location: Bucharest, Romania
map-lat: 44.4267674
map-lng: 26.102538399999958

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these

ga:
  code: UA-111447513-1

####
#
# Hi you now use Sera - OnePage Jekyll Template created by Gleesik™
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
about-title: Welcome
about-description: "During this course, you will be introduced to the many techniques and best practices that I've
learned throughout my coding journey.  Together we will work on refactoring a legacy project, building a new one from
 scratch and designing complex architecture. We will focus on using simple, practical models and processes that are
 applicable in any software application​."
about-description-2: "Through every step of this journey, we will critique what is the right path to take to solve
technical problems such that you are adequately equipped to take on complex of software projects."

questions:

- title: Are you creating more bugs than you're fixing?
- title: Do you feel uncomfortable receiving feedback on your code?
- title: Are you stuck with complex software that needs refactoring?
- title: Do you want to improve your skills to keep up with best practises?


#####################################
#############  Features  ############
#####################################
features-title: Benefits
features-description: "I want this course to be as practical as possible. By joining <strong>$this</strong> course
you will gain:"

#
# Features
#
features:

# Feature
- title: Hours of best practices
  description: All content is hosted on Udemy platform as videos. You can watch on any device and an average video length is 7 mins. One video a day, sends spaghetti code away.
  icon: pe-7s-video

# Feature
- title: Personal Support
  description: "I was in your shoes few years ago. I remember very well how many questions did I have to ask my
  teammates in my first job. If you have any question or a doubt, I will be there for YOU, answering questions 24/7."
  icon: pe-7s-user


#####################################
############  Portfolio  ############
#####################################
portfolio-title: Free course content preview
portfolio-description: Don't take my word for it. Even though you have 100% money back guarantee, I want to be as fair as possible. Have a look yourself what will you get. I made one video of each course section free to watch. I am fully confident the content of <strong>$this</strong> course will help you <strong>progress</strong> in your career!

#
# Portfolio Grid
#
portfolio-categories: [Clean code, SOLID, Design Patterns, Architecture]
portfolio:

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Websites, Graphic Design]
  image: img-01.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Graphic Design, Logo, Websites]
  image: img-02.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Graphic Design, Logo, Photography]
  image: img-03.jpg
  url: '#'

- title: S<span class="thin">era</span> Style
  categories: [Websites, Video, Photography]
  image: img-04.jpg
  url: '#'

- title: S<span class="thin">era</span> Style
  categories: [Development, Logo]
  image: img-05.jpg
  url: '#'

#####################################
##########  Core Features  ##########
#####################################
core-title: Content
core-description: The material for this course is based on the 80/20 rule. As such, you should not be expected to know thousands of design patterns to write excellent software. Instead, your goal should be to know the most commonly used principles that are considered best-practice within the software engineering community.

#
# Core Features Left
#
core-features-left:


# Feature
- name: Code review the right way
  description: The mindset and my tips whenever you are the author or the reviewer.
  icon: pe-7s-glasses

# Feature
- name: Coding standards
  description: All code in your project should be written in the same way.
  icon: pe-7s-note2

# Feature
- name: Daily Clean code
  description: The fundamentals of good software is proper naming. No excuses.
  icon: pe-7s-anchor

# Feature
- name: Designing Scope 101
  description: You will learn how to ensure proper encapsulation.
  icon: pe-7s-safe

#
# Core Features Right
#
core-features-right:

# Feature
- name: MySQL in Docker
  description: Isolate your environements so your team has the same infrastructure.
  icon: pe-7s-server

# Feature
- name: S.O.L.I.D Principles
  description: Together, we will refactor a legacy codebase step by step.
  icon: pe-7s-paint

# Feature
- name: Design Patterns, Symfony
  description: Don't re-invent solutions. Apply industry standards.
  icon: pe-7s-piggy

# Feature
- name: Architecture
  description: You will be able to design ANY system regardless its complexity.
  icon: pe-7s-display1

#####################################
########### Testimonials ############
#####################################
testimonials-title: Testimonials
testimonials-description: Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi.

#
# Testimonials
#
testimonials:

# Client
- name: Johnatan Doe
  url: http://themeforest.net
  url-text: ThemeForest.net
  avatar: avatar-01.jpg
  cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
  logo-img: themeforest.png

# Client
- name: Adam Smith
  url: http://codecanyon.net
  url-text: CodeCanyon.net
  avatar: avatar-02.jpg
  cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
  logo-img: codecanyon.png

# Client
- name: Irene Warner
  url: http://videohive.net
  url-text: VideoHive.net
  avatar: avatar-03.jpg
  cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
  logo-img: videohive.png

# Client
- name: Richard Ryan
  url: http://audiojungle.net
  url-text: AudioJungle.net
  avatar: avatar-04.jpg
  cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
  logo-img: audiojungle.png


#####################################
############# Our Blog ##############
#####################################
blog-title: Blog
blog-description: “... a mind needs books as a sword needs a whetstone, if it is to keep its edge.”


#####################################
############### Team ################
#####################################
team-title: About the author
team-description: "Hi, I am Lukas!"
team-description-2: "I work at trivago as a technical lead on a project that directly contributes to 40% of all of
trivago's incoming traffic."
team-description-3: "Previous to this role I was the technical lead on a bidding platform that was responsible for
processing millions of bids each day from advertisers such as booking.com and expedia.com."
team-description-4: "I started mentoring developers as part of my day to day responsibilities at trivago. Helping
others grew into a passion and I have since become a Udemy instructor."
team-description-5: "I am looking forward to working with you!"


#
# Team Members
#
team:

# Team Member
- name: Lukas Lukac
  tagline: Technical Lead
  avatar: lukas_lukac_profile.jpg

  # Social Links
  facebook: 'https://facebook.com/lukas.lukac'
  twitter: 'https://twitter.com/EnchanterIO'
  linkedin: 'https://www.linkedin.com/in/llukac'

#
# 365 development tips
#
tips_365:
- id: 1
  description: A Domain Object represents my domain and is UNAWARE of storage and persistence.
  date: 01.01.2018

- id: 2
  description: No, Microservices won't fix your broken monolith. Proper Scope encapsulation, S.O.L.I.D principles and Design Patterns will.
  date: 02.01.2018

- id: 3
  description: Setters in OOP is just pure evil. Setters and that unfortunate USA president.
  date: 03.01.2018

- id: 4
  description: "As a software/hardware engineer building products FOR PEOPLE you should strive for QUALITY > quantity.
  Right Intel/Apple/Every damn company after year 2000?"
  date: 04.01.2018

- id: 5
  description: "A Class name should be a noun."
  date: 05.01.2018

- id: 6
  description: "Don’t accept illogical tasks! | Moein Akbarof"
  date: 06.01.2018

- id: 7
  description: "Use Composer to manage your dependencies and for Class auto-loading. https://dev.to/enchanterio/the-magic-behind-autoloading-php-files-using-composer-1e19"
  date: 07.01.2018

- id: 8
  description: Avoid NULL. No Null, no need for IF(is_null(...)) condition, always valid state, no problem.
  date: 08.01.2018

- id: 9
  description: Your soft skills are as important as your technical skills.
  date: 09.01.2018

- id: 10
  description: Always consider what project parts could be affected by your code change before doing so.
  date: 10.01.2018

- id: 11
  description: Don’t trust other developers nor yourself. Always double check the code you rely on.
  date: 11.01.2018

- id: 12
  description: Use CodeSniffer to ensure a consistent code style across your codebase.
  source: https://www.udemy.com/enterprise-php/learn/v4/t/lecture/8531870
  date: 12.01.2018

- id: 13
  description: Treat your *Repository as a Collection.
  date: 13.01.2018

- id: 14
  description: Software design, documentation is perfectly Agile, Scrum sprint compatible.
  source: https://enterprise-level-php.com/2018/01/13/the-agile-misconception-of-documentation-and-software-design.html
  date: 14.01.2018

- id: 15
  description: "Build a habit of diving into vendors, libraries occasionally, if time permits, instead of just googling
  answers. You will learn and expand your vision much more."
  date: 15.01.2018

- id: 16
  description: "As stubborn as we developers are, taking a short-mid break from a logical world of programming often
  leads to the most elegant solutions."
  source: https://twitter.com/EnchanterIO/status/953273105836924928
  date: 16.01.2018

- id: 17
  description: "As a Class should have 1 responsibility, a technical diagram should have 1 purpose. Avoid
  mixing different level of details in 1 canvas."
  source: https://c4model.com
  date: 17.01.2018


#####################################
########## Target audience ###########
#####################################
audience-title: Is this course for me?
audience-description: If you invest in yourself today, your skills and experience will pay off tomorrow.

#####################################
########## Pricing Tables ###########
#####################################
pricing-title: Course prices
pricing-description: If you invest in yourself today, your skills and experience will pay off tomorrow.

#
# Plan Personal
#
plan-regular-price: $29
plan-regular-url: 'https://www.udemy.com/enterprise-php/'

#
# Plan Business
#
plan-sale-price: $19
plan-sale-url: 'https://www.udemy.com/enterprise-php/?couponCode=FIRST_50_STUDENTS'

#
# Plan Mentor
#
plan-mentor-price: $99
plan-mentor-url: 'services@trki.sk'

#####################################
############   Contact   ############
#####################################
contact-title: Wanna talk?
contact-description: Are you missing something in the course? Do you have a doubt? Are you looking for a mentor? Let's get in touch.


#####################################
#############   Footer   ############
#####################################
footer-description: "Course <strong>Writing Enterprise Level PHP Code</strong> is designed for YOU!"
footer-description2: "Below is my Twitter account. Write me a message at ANY time you have a question, doubt, idea
regarding the course OR you want to discuss ANY other topic. Looking forward our geeky discussion!"
footer-copyright-text: Lukas Lukac
footer-copyright-url: https://www.linkedin.com/in/llukac
footer-copyright-year: 2017-2018
