#
# Sera - OnePage Jekyll Template
# Configuration File
#

# Information for compile
exclude: ["node_modules", "gulpfile.js", "package.json", "README.md"]

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: "Course: Writing Enterprise Level PHP"
description: "Learn how to write HQ maintainable software. Legacy code doesn't have to suck!"
default_blog_image: enterprise_level_php_course_thumbnail.jpg
# Website language
lang: en-US
# Header Title
header-title: Enterprise Level <strong>PHP</strong>
# Header Tagline
headter-tagline: Course

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: I want it!
  url: https://www.udemy.com/enterprise-php/

# Secondary Buttons
header-secondary-button:
  title: Hm, Tell me more
  url: "#about"

#
# If your website is placed in a separate folder on your server please modify
# this with your folder name, by default is empty.
# Example: Sera Demo is hosted on projects.gleesik.ro/sera-onepage
# If I compile Sera Template and I put in /sera-onepage without modifing baseurl
# than scripts can't be loaded corectly.
# For this example my site url is: projects.gleesik.ro (This can be just www.example.com)
# My folder for Demo Website is: /sera-onepage so baseurl: /sera-onepage
#
baseurl:

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: services@trki.sk

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: https://www.udemy.com/enterprise-php/

####################################
######  Global Social Links   ######
####################################
youtube: '#'
pinterest: '#'
facebook: 'https://www.facebook.com/lukas.lukac'
twitter: 'https://twitter.com/EnchanterIO'
twitter_username: 'EnchanterIO'
linkedin: 'https://www.linkedin.com/in/llukac'
google-plus: '#'
vimeo: '#'

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: lukas_lukac_profile.jpg
  author-name: Lukas Lukac
  author-tagline: Course Instructor
  author-info: Software Engineering, Psychology, Starcraft, Protein, Women && Motorbikes addict.
  author-social-links:
    youtube: '#'
    pinterest: '#'
    facebook: 'https://www.facebook.com/lukas.lukac'
    twitter: 'https://twitter.com/EnchanterIO'
    linkedin: 'https://www.linkedin.com/in/llukac'
    google-plus: '#'

# Google Map JS api
# This is my api for this template
key-api: AIzaSyDbnxVZQannH0GF4gtnnBFPiP9ofm2WqGs
map-text: Sera Google Map
map-text-location: Bucharest, Romania
map-lat: 44.4267674
map-lng: 26.102538399999958

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these

ga:
  code: UA-111447513-1

####
#
# Hi you now use Sera - OnePage Jekyll Template created by Gleesik™
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
about-title: Welcome
about-description: In this course I will teach you everything I teach my colleagues on daily basis at trivago. You will watch me refactoring legacy project, building a new one from scratch and designing complex architecture using simple, practical model applicable everywhere​. You will hear me explaining what's the advantage of every single technique. You will learn the <strong>WHY</strong>, <strong>HOW</strong> and also the <strong>WHEN</strong>.
about-description-2: <strong>You will learn how to write high quality, maintainable software you will be proud of. Legacy code doesn't have to suck!</strong>

questions:

# Feature
- title: How easy are you able to add a feature into your existing project?
  description: 'If the answer is: "Well, after 5x WTF, what the hell, why this bug again, you are able to add it." then you are in a good place.'

- title: Are you proud of the code you are writing? Are you well paid?
  description: I was there as well. 4 years ago. It sucks. Writing average code and afraid of feedback. <strong>Don't worry!</strong> It's normal. You just need a mentor, enthusiasm and a bit of practice.


#####################################
#############  Features  ############
#####################################
features-title: Benefits
features-description: "I want this course to be as practical as possible. You are a <strong>developer</strong>, not an academic! By joining <strong>$this</strong> course you will get:"

#
# Features
#
features:

# Feature
- title: Hours of best practices
  description: All content is hosted on Udemy platform as videos. You can watch on any device and an average video length is 7 mins. One video a day, sends spaghetti code away.
  icon: pe-7s-video

# Feature
- title: Personal Support
  description: I was in your shoes few years ago. I remember very well how many questions did I have to ask my teammates in my first job. If you have any question, a doubt, I will be there for YOU, answering questions 24/7.
  icon: pe-7s-user


#####################################
############  Portfolio  ############
#####################################
portfolio-title: Free course content preview
portfolio-description: Don't take my word for it. Even though you have 100% money back guarantee, I want to be as fair as possible. Have a look yourself what will you get. I made one video of each course section free to watch. I am fully confident the content of <strong>$this</strong> course will help you <strong>progress</strong> in your career!

#
# Portfolio Grid
#
portfolio-categories: [Clean code, SOLID, Design Patterns, Architecture]
portfolio:

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Websites, Graphic Design]
  image: img-01.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Graphic Design, Logo, Websites]
  image: img-02.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Graphic Design, Logo, Photography]
  image: img-03.jpg
  url: '#'

- title: S<span class="thin">era</span> Style
  categories: [Websites, Video, Photography]
  image: img-04.jpg
  url: '#'

- title: S<span class="thin">era</span> Style
  categories: [Development, Logo]
  image: img-05.jpg
  url: '#'

#####################################
##########  Core Features  ##########
#####################################
core-title: Content
core-description: The material is prepared using 80:20 rule. You don't need to know 3485793 design patterns to write excellent software. You need to know the main and the most commonly used principles to solve day to day business challenges.

#
# Core Features Left
#
core-features-left:


# Feature
- name: Code review the right way
  description: The mindset and my tips whenever you are the author or the reviewer.
  icon: pe-7s-glasses

# Feature
- name: Coding standards
  description: All code in your project should be written in the same way.
  icon: pe-7s-note2

# Feature
- name: Daily Clean code
  description: The fundamentals of good software is proper naming. No excuses.
  icon: pe-7s-anchor

# Feature
- name: Designing Scope 101
  description: You will learn how to ensure proper encapsulation.
  icon: pe-7s-safe

#
# Core Features Right
#
core-features-right:

# Feature
- name: MySQL in Docker
  description: Isolate your ENV and ensure your team has the same infrastructure.
  icon: pe-7s-server

# Feature
- name: S.O.L.I.D Principles
  description: You will see me applying each principle in a legacy codebase.
  icon: pe-7s-paint

# Feature
- name: Design Patterns, Symfony
  description: Don't reinvent solutions. Your code challenges were already solved.
  icon: pe-7s-piggy

# Feature
- name: Architecture
  description: You will be able to design ANY system regardless its complexity.
  icon: pe-7s-display1

#####################################
########### Testimonials ############
#####################################
testimonials-title: Testimonials
testimonials-description: Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi.

#
# Testimonials
#
testimonials:

# Client
- name: Johnatan Doe
  url: http://themeforest.net
  url-text: ThemeForest.net
  avatar: avatar-01.jpg
  cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
  logo-img: themeforest.png

# Client
- name: Adam Smith
  url: http://codecanyon.net
  url-text: CodeCanyon.net
  avatar: avatar-02.jpg
  cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
  logo-img: codecanyon.png

# Client
- name: Irene Warner
  url: http://videohive.net
  url-text: VideoHive.net
  avatar: avatar-03.jpg
  cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
  logo-img: videohive.png

# Client
- name: Richard Ryan
  url: http://audiojungle.net
  url-text: AudioJungle.net
  avatar: avatar-04.jpg
  cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
  logo-img: audiojungle.png


#####################################
############# Our Blog ##############
#####################################
blog-title: Blog
blog-description: “... a mind needs books as a sword needs a whetstone, if it is to keep its edge.”


#####################################
############### Team ################
#####################################
team-title: About the author
team-description: "Hi, I'm Lukas! Currently a Technical lead at a core trivago project even though only 4 years ago I started as a Junior developer fixing bugs."
team-description-2: "In last 2 years I rebuilt a legacy bidding application processing millions of bids each day from advertisers such a Booking.com and now I am designing/developing a tool uploading hundreds of millions ads daily to Google."
team-description-3: "I started mentoring developers as part of my responsibilities at trivago and helping others grew into a passion so I became a Udemy instructor."
team-description-4: "This course has one purpose. To show you how to write maintainable software you will be proud of. Legacy code doesn't have to suck."
team-description-5: "Looking for our cooperation!"


#
# Team Members
#
team:

# Team Member
- name: Lukas Lukac
  tagline: Technical Lead
  avatar: lukas_lukac_profile.jpg

  # Social Links
  facebook: 'https://facebook.com/lukas.lukac'
  twitter: 'https://twitter.com/EnchanterIO'
  linkedin: 'https://www.linkedin.com/in/llukac'

#
# 365 development tips
#
tips_365:
- id: 1
  description: A Domain Object represents my domain and is UNAWARE of storage and persistence.
  date: 01.01.2018

- id: 2
  description: No, Microservices won't fix your broken monolith. Proper Scope encapsulation, S.O.L.I.D principles and Design Patterns will.
  date: 02.01.2018

- id: 3
  description: Setters in OOP is just pure evil. Setters and that unfortunate USA president.
  date: 03.01.2018

- id: 4
  description: "As a software/hardware engineer building products FOR PEOPLE you should strive for QUALITY > quantity.
  Right Intel/Apple/Every damn company after year 2000?"
  date: 04.01.2018

- id: 5
  description: "A Class name should be a noun."
  date: 05.01.2018

- id: 6
  description: "Don’t accept illogical tasks! | Moein Akbarof"
  date: 06.01.2018

- id: 7
  description: "Use Composer to manage your dependencies and for Class auto-loading. https://dev.to/enchanterio/the-magic-behind-autoloading-php-files-using-composer-1e19"
  date: 07.01.2018

- id: 8
  description: Avoid NULL. No Null, no need for IF(is_null(...)) condition, always valid state, no problem.
  date: 08.01.2018

#This could be useful when I write a page about the C4 model
#- id: 8
#  description: As a Class, Object should have one responsibility, a technical diagram should have one purpose. Avoid
#  mixing different level of details in one canvas.
#  date: 08.01.2018


#####################################
########## Target audience ###########
#####################################
audience-title: Is this course for me?
audience-description: Investing in yourself few dollars now, will generate you thousands dollars in the future.

#####################################
########## Pricing Tables ###########
#####################################
pricing-title: Course prices
pricing-description: Investing in yourself few dollars now, will generate you thousands dollars in the future.

#
# Plan Personal
#
plan-regular-price: $29
plan-regular-url: 'https://www.udemy.com/enterprise-php/'

#
# Plan Business
#
plan-sale-price: $19
plan-sale-url: 'https://www.udemy.com/enterprise-php/?couponCode=FIRST_50_STUDENTS'


#####################################
############   Contact   ############
#####################################
contact-title: Wanna talk?
contact-description: Are you missing something in the course? Do you have a doubt? Are you looking for a mentor? Let's get in touch.


#####################################
#############   Footer   ############
#####################################
footer-description: "Course <strong>Writing Enterprise Level PHP Code</strong> is designed for YOU!"
footer-description2: "Below is my Twitter account. Write me a message ANY time you have a question, doubt, idea
regarding the course OR you want to discuss ANY other topic. Looking forward our geeky discussion!"
footer-copyright-text: Lukas Lukac
footer-copyright-url: https://www.linkedin.com/in/llukac
footer-copyright-year: 2017-2018
